//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfferCustomTexts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfferCustomTexts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name is not valid..
        /// </summary>
        internal static string ColumnNameIsNotValid {
            get {
                return ResourceManager.GetString("ColumnNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML.
        /// </summary>
        internal static string ExportXml {
            get {
                return ResourceManager.GetString("ExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For all).
        /// </summary>
        internal static string ForAllProfiles {
            get {
                return ResourceManager.GetString("ForAllProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For all).
        /// </summary>
        internal static string ForAllReports {
            get {
                return ResourceManager.GetString("ForAllReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported dataset contains one or more new columns. Do you want to create them?.
        /// </summary>
        internal static string HasNewColumns {
            get {
                return ResourceManager.GetString("HasNewColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import XML.
        /// </summary>
        internal static string ImportXml {
            get {
                return ResourceManager.GetString("ImportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing text....
        /// </summary>
        internal static string ParsingText {
            get {
                return ResourceManager.GetString("ParsingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete selected custom text?.
        /// </summary>
        internal static string ReallyDeleteText {
            get {
                return ResourceManager.GetString("ReallyDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports - custom header and footer texts.
        /// </summary>
        internal static string ReportsCustomTexts {
            get {
                return ResourceManager.GetString("ReportsCustomTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports - user data.
        /// </summary>
        internal static string ReportsUserData {
            get {
                return ResourceManager.GetString("ReportsUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files.
        /// </summary>
        internal static string XmlFiles {
            get {
                return ResourceManager.GetString("XmlFiles", resourceCulture);
            }
        }
    }
}
